import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: [
    ".adal/**",
    ".agent/**",
    ".agents/**",
    ".aider-desk/**",
    ".augment/**",
    ".autohand/**",
    ".bob/**",
    ".claude/**",
    ".codeartsdoer/**",
    ".codebuddy/**",
    ".codemaker/**",
    ".codestudio/**",
    ".commandcode/**",
    ".continue/**",
    ".cortex/**",
    ".crush/**",
    ".cursor/**",
    ".devin/**",
    ".factory/**",
    ".forge/**",
    ".gemini/**",
    ".github/**",
    ".goose/**",
    ".grok/**",
    ".hermes/**",
    ".iflow/**",
    ".inferencesh/**",
    ".jazz/**",
    ".junie/**",
    ".kilocode/**",
    ".kimchi/**",
    ".kimi/**",
    ".kimi-code/**",
    ".kiro/**",
    ".kode/**",
    ".lingma/**",
    ".mcpjam/**",
    ".minimax/**",
    ".moxby/**",
    ".mux/**",
    ".neovate/**",
    ".ona/**",
    ".opencode/**",
    ".openhands/**",
    ".pi/**",
    ".pochi/**",
    ".posit/**",
    ".qoder/**",
    ".qwen/**",
    ".reasonix/**",
    ".roo/**",
    ".rovodev/**",
    ".serena/**",
    ".tabnine/**",
    ".terramind/**",
    ".tinycloud/**",
    ".trae/**",
    ".vibe/**",
    ".vscode/**",
    ".windsurf/**",
    ".zcode/**",
    ".zencoder/**",
    "agent/**",
    "data/**",
    "node_modules/**",
    "skills/**",
    "tools/oxlint/anti-slop/**",
    "tools/cloudflare-runtime/**",
    "tools/celld-runtime/**",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
});
